# Generated by Django 2.0 on 2018-12-26 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('about_author', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='p', max_length=1)),
                ('cost', models.FloatField(max_length=5)),
                ('currency', models.CharField(max_length=10)),
                ('publish_date_time', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
                ('genre_details', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['genre_name'],
            },
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenre_name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=500)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='sub_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.SubGenre'),
        ),
    ]
