# Generated by Django 2.0 on 2018-12-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181226_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
    ]
