# Generated by Django 2.0 on 2018-12-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181226_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='sub_genre',
            new_name='subgenre_name',
        ),
    ]
