# Generated by Django 2.0 on 2018-12-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20181226_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date_time',
            field=models.DateTimeField(),
        ),
    ]
