# Generated by Django 2.0 on 2018-12-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20181227_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date_time',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
